# Generated by Django 5.0.4 on 2024-04-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='Salma', max_length=100)),
                ('familyName', models.CharField(default='Hany', max_length=100)),
                ('phoneNumber', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
                ('Nationality', models.CharField(default='Egyptian', max_length=100)),
                ('gamil', models.CharField(default='add your gmail', max_length=150)),
                ('password', models.CharField(default='add your password', max_length=150)),
                ('re_password', models.CharField(default='confirm your password', max_length=150)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('candidateName', models.CharField(blank=True, choices=[('sisi', 'Sisi'), ('hazem', 'Hazem'), ('abd el sanad', 'Abd El Sanad'), ('mohamed', 'Mohamed')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='N_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('familyName', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
                ('Nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gamil', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('re_password', models.CharField(blank=True, max_length=150, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
