# Generated by Django 5.0.4 on 2024-04-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_datastored_election_n_id_voter_alter_car_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='birth',
            field=models.DateField(default='2002-04-16'),
        ),
    ]
