# Generated by Django 5.0.4 on 2024-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_voter_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastored',
            name='birth',
            field=models.DateField(default='2002-04-16'),
        ),
    ]
